apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: PDEE91DDB90597936
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      defaultDatabase: ${CLICKHOUSE_DB}
      protocol: http
      host: clickhouse
      port: 8123
      username: default
      tlsSkipVerify: true
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
